/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    InspectorDataTreeNode: typeof import('./features/inspector/DataTreeNode.vue')['default']
    InspectorFeatureWorkbench: typeof import('./features/inspector/FeatureWorkbench.vue')['default']
    InspectorFieldDetailPanel: typeof import('./features/inspector/FieldDetailPanel.vue')['default']
    InspectorInspectorView: typeof import('./features/inspector/InspectorView.vue')['default']
    InspectorRawViewer: typeof import('./features/inspector/RawViewer.vue')['default']
    InspectorWatchButton: typeof import('./features/inspector/WatchButton.vue')['default']
    NetworkNetworkView: typeof import('./features/network/NetworkView.vue')['default']
    ThemeController: typeof import('./components/theme-controller.vue')['default']
  }
}
